---
- name: Playbook for EAP Hosts
  hosts: eap
  become: yes
  roles:
    - redhat.eap.eap_install
    - redhat.eap.eap_driver
    - redhat.eap.eap_systemd
  pre_tasks:
    - name: Enable and start the firewalld service
      become: yes
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
        state: started
    - name: "Configure firewall for EAP ports"
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: yes
      loop:
        - 8009/tcp
        - 8080/tcp
        - 9990/tcp

- name: Playbook for EAP Hosts config and app deployment
  hosts: eap
  become: yes
  serial: 1
  tasks:
    - name: Verify service is started
      ansible.builtin.service:
        name: jbcs-eap
        state: started
      throttle: 1
    - name: Verify management port is accessible
      ansible.builtin.wait_for:
        port: 9990
        host: localhost
        connect_timeout: 3
        delay: 10
        timeout: 60
    - name: "Download demo app to deploy from {{ app_url }} into deployments"
      ansible.builtin.get_url:
        url: "{{ app_url }}"
        dest: "{{ eap.home }}/standalone/deployments/addressbook.war"
        owner: eap
        group: eap
        mode: 0644
