---
collections:
  - name: redhat.runtimes_common
    version: "==1.1.0"
  - name: redhat.sso
    version: "==1.2.6"
  - name: redhat.eap
    version: "==1.3.3"
  - name: middleware_automation.jbcs
    version: "==1.0.2"
