---
collections:
  - name: redhat.runtimes_common
    version: "==1.1.0"
  - name: redhat.sso
    src: https://github.com/guidograzioli/keycloak/raw/instruqt/redhat-sso-1.2.7.tar.gz
  - name: redhat.eap
    src: https://github.com/guidograzioli/keycloak/raw/instruqt/redhat-eap-1.3.3.tar.gz
  - name: middleware_automation.jbcs
    version: "==1.0.2"
