---
collections:
  - name: redhat.runtimes_common
    version: "==1.1.0"
#  - name: redhat.sso
  - name: https://github.com/guidograzioli/keycloak/raw/instruqt/redhat-sso-1.2.7.tar.gz
    type: url
#  - name: redhat.eap
  - name: https://github.com/guidograzioli/keycloak/raw/instruqt/redhat-eap-1.3.3.tar.gz
    type: url
  - name: middleware_automation.jbcs
    version: "==1.0.2"
