---
collections:
#  - name: redhat.sso
  - name: https://github.com/guidograzioli/keycloak/raw/instruqt/redhat-sso-1.2.7.tar.gz
    type: url
#  - name: redhat.eap
  - name: https://github.com/guidograzioli/keycloak/raw/instruqt/redhat-eap-1.3.3.tar.gz
    type: url
#  - name: redhat.runtimes_common
  - name: https://github.com/guidograzioli/keycloak/raw/instruqt/redhat-runtimes_common-1.1.4.tar.gz
    type: url
#  - name: middleware_automation.jbcs
  - name: https://github.com/guidograzioli/keycloak/raw/instruqt/middleware_automation-jbcs-1.1.0.tar.gz
    type: url
  - name: https://github.com/guidograzioli/keycloak/raw/instruqt/ansible-posix-1.4.0.tar.gz
    type: url
