---
- name: Playbook for rhsso Hosts
  hosts: sso
  become: true
  tasks:
    - name: "Run the realm configuration"
      ansible.builtin.include_role:
        name: redhat.sso.sso_realm
        apply:
          delegate_to: "{{ ansible_play_hosts | first }}"
          run_once: true
      vars:
        sso_admin_password: "{{ admin_pass }}"
        sso_realm: addressbook
        sso_clients: "{{ realm_clients }}"
