plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
  - us-west-2
filters:
  tag:Created-By: ansible
  tag:Application: multicloud-sso-datagrid
hostnames:
  - tag:Name
leading_separator: no
keyed_groups:
 - key: tags.Role
 - key: tags.Site
 - key: placement.region
 - key: tags.Cloud
# Ignores 403 errors rather than failing
strict_permissions: False
compose:
  ansible_host: public_ip_address
