---
jvm_package: java-11-openjdk-headless
domain_name: '.internal.ansiblemiddleware.com'
external_domain_name: "jbcs-eap-443-{{ lookup('template', 'student_id') }}.env.play.instruqt.com"
site_jdbc_url: "jdbc:postgresql://jbcs-eap:5432"
sso_frontend_url: "https://{{ external_domain_name }}/auth/"
sso_admin_user: admin
