---
admin_pass: admin_password
user_accounts:
  - { name: 'ggraziol', password: 'adminpassword', roles: 'admin' }
  - { name: 'rpelisse', password: 'password', roles: 'observer' }
  - { name: 'ablock', password: 'password', roles: 'observer' }
  - { name: 'hcheruku', password: 'password', roles: 'observer' }
  - { name: 'rhsso', password: 'rhssopassword', roles: 'application' }

data_grid_keycloak_caches: True
data_grid_configure_firewalld: True
data_grid_keycloak_persistence: False
data_grid_offline_install: False
data_grid_jgroups_relay: True
data_grid_jgroups_relay_sites:
  - site1
  - site2
  - site3
  - site4

data_grid_db_user: keycloak-user
data_grid_db_pass: keycloak-pass

data_grid_jdbc_url: "{{ site_jdbc_url }}/keycloak?socketTimeout=10000"

data_grid_default_realm_tls: True
data_grid_keystore_path: /etc/pki/java/keystore.jks
data_grid_keystore_alias: "*{{ domain_name }}"

install_keystore: True

data_grid_bind_address: "{{inventory_hostname}}{{domain_name}}"
data_grid_url: "https://{{inventory_hostname}}{{domain_name}}:11222"
