---
sso_ha_enabled: True
sso_remote_cache_enabled: False
sso_configure_firewalld: True
sso_offline_install: False
sso_management_port_bind_address: 0.0.0.0
sso_http_port: 8081
sso_modcluster_url: "jbcs-eap"

sso_jdbc_engine: postgres
sso_jdbc_url: "{{ site_jdbc_url }}/keycloak"
sso_db_user: keycloak-user
sso_db_pass: keycloak-pass
sso_db_background_validate_on_match: True
sso_db_valid_conn_sql: 'SELECT 1'
sso_jgroups_subnet: "{{ (ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0])) + '/24' }}"

admin_pass: "redhat1!but12long"

realm_clients:
  - name: addressbook
    client_id: addressbook
    roles:
      - admin_role
      - user_role
    realm: addressbook
    public_client: true
    web_origins: '+'
    redirect_uris: '*'
    users:
      - username: administrator
        email: ansible-middleware-core@redhat.com
        firstName: Admin
        lastName: Admin
        password: password
        client_roles:
          - client: addressbook
            role: admin_role
            realm: addressbook
          - client: addressbook
            role: user_role
            realm: addressbook
      - username: user
        email: ggraziol@redhat.com
        firstName: Guido
        lastName: Grazioli
        password: password
        client_roles:
          - client: addressbook
            role: user_role
            realm: addressbook